SweetTreat/Models/Flavor.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SweetTreat.Models
{
  public class Flavor
  {
    public int FlavorId { get; set; }
     [Required(ErrorMessage = "The flavor's name can't be empty!")]
    public string Name { get; set; }
    public Treat Treat { get; set; }
    public List<FlavorTreat> JoinEntities { get;}
    public ApplicationUser User { get; set; }
  }
}

SweetTreat/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Mvc;
using SweetTreat.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace SweetTreat.Controllers
{
  [Authorize]
  public class FlavorsController : Controller
  {
    private readonly SweetTreatContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public FlavorsController(UserManager<ApplicationUser> userManager, SweetTreatContext db)
    {
      _userManager = userManager;
      _db = db;
    }
    
    public async Task<ActionResult> Index()
    {
      string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);
      List<Flavor> userFlavors = _db.Flavors
                          .Where(entry => entry.User.Id == currentUser.Id)
                          .Include(flavor => flavor.JoinEntities)
                          .ThenInclude(join => join.Treat)
                          .ToList();
      return View(userFlavors);
    }

    public ActionResult Details(int id)
    {
      Flavor thisFlavor = _db.Flavors
          .Include(flavor => flavor.JoinEntities)
          .ThenInclude(join => join.Treat)
          .FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    public ActionResult Create()
    {
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "Name");
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Flavor flavor)
    {
      if (!ModelState.IsValid)
      {
        ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "Name");
        return View(flavor);
      }
      else
      {
        string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);
        flavor.User = currentUser;
        _db.Flavors.Add(flavor);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
    }

    public ActionResult AddTreat(int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavors => flavors.FlavorId == id);
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "Name");
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult AddTreat(Flavor flavor, int treatId)
    {
      #nullable enable
      FlavorTreat? joinEntity = _db.FlavorTreats.FirstOrDefault(join => (join.TreatId == treatId && join.FlavorId == flavor.FlavorId));
      #nullable disable
      if (joinEntity == null && treatId != 0)
      {
        _db.FlavorTreats.Add(new FlavorTreat() { TreatId = treatId, FlavorId = flavor.FlavorId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = flavor.FlavorId });
    }

    public ActionResult Edit(int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavors => flavors.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult Edit(Flavor flavor)
    {
      _db.Flavors.Update(flavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavors => flavors.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavors => flavors.FlavorId == id);
      _db.Flavors.Remove(thisFlavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      FlavorTreat joinEntry = _db.FlavorTreats.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
      _db.FlavorTreats.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

SweetTreat/Views/Flavors/AddTreat.cshtml
@{
  Layout = "_Layout";
}

@model SweetTreat.Models.Flavor

<h2>Add a treat</h2>

<h4>Add a treat to this flavor: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.FlavorId)

    @Html.Label("Select treat")
    @Html.DropDownList("TreatId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

SweetTreat/Views/Flavors/Create.cshtml
@{
  Layout = "_Layout";
}

@model SweetTreat.Models.Flavor

<h4>Add a new flavor</h4>

@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)

    <input type="submit" value="Add new flavor" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all flavors", "Index")</p>

SweetTreat/Views/Flavors/Delete.cshtml
@{
  Layout = "_Layout";
}

@model SweetTreat.Models.Flavor

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

SweetTreat/Views/Flavors/Details.cshtml
@{
  Layout = "_Layout";
}

@using SweetTreat.Models
@model SweetTreat.Models.Flavor

<h2>Flavor Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This flavor does not belong to any treats</p>
}
else
{
  <h4>Treats the flavor belongs to:</h4>
  <ul>
  @foreach(FlavorTreat join in Model.JoinEntities)
  {
    <li>@join.Treat.Name</li>
    @using (Html.BeginForm("DeleteJoin", "Flavors"))
    {
      @Html.Hidden("joinId", @join.FlavorTreatId)
      <input type="submit" value="Delete"/>
    }
  }
  </ul>
}

<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Add a treat", "AddTreat", new { id = Model.FlavorId })</p>
<p>@Html.ActionLink("Edit Flavor", "Edit", new { id = Model.FlavorId })</p>
<p>@Html.ActionLink("Delete Flavor", "Delete", new { id = Model.FlavorId })</p>

SweetTreat/Views/Flavors/Edit.cshtml
@{
  Layout = "_Layout";
}

@model SweetTreat.Models.Flavor

<h2>Edit</h2>

<h4>Edit this flavor: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.FlavorId)

    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name)

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

SweetTreat/Views/Flavors/Index.cshtml
@{
  Layout = "_Layout";
}

@using SweetTreat.Models;

<h1>Flavors</h1>

@if (@Model.Count == 0)
{
  <h3>No flavors have been added yet!</h3>
} 

@foreach (Flavor flavor in Model)
{
  <li>@Html.ActionLink($"{flavor.Name}", "Details", new { id = flavor.FlavorId })</li>
}

<p>@Html.ActionLink("Add new flavor", "Create")</p>

<p>@Html.ActionLink("Home", "Index", "Home")</p>